- package-lock.json
- package.json
- pnpm-lock.yaml
- src/App.css
- src/App.tsx
- src/Bienvenida.tsx
- src/Login.tsx
- src/adapter.tsx
- src/index.css
Aqui se añade el login funcional, 
-puede comunicarse con la API
-mostrar mensajes de error
-guardar el usuario en el contexto
-css
> Login implementation

- src/App.tsx
- src/Bienvenida.tsx
- src/Login.tsx
- src/adapter.tsx
Adaptador para datos que vienen del backend para usuarios
- Incluye un adaptador generico para cualquier dato que venga del backend
- Incluye el adaptador especifico para usuario
- Cambios en el código para utilizarse
> feat: adaptador de datos de backend a frontend

- src/adapter.tsx
- src/hooks/useRoles.ts
- src/interfaces/ErrorResponse.ts
- src/interfaces/Role.ts
- src/pages/userPages/UserOptionCreate.tsx
- src/services/roles/getRoles.service.ts
- src/services/roles/index.ts
Descripción:
Resumen:
Se implementa un servicio y un custom hook para obtener los roles de usuario desde el backend en el frontend.
Facilitar la gestión y visualización de los roles de usuario en el frontend, mejorando la interacción y funcionalidad de la aplicación.
Implementado servicio getRoles para realizar solicitudes al endpoint correspondiente del backend.
Creado custom hook useRoles para manejar la lógica de obtención y estado de los roles de usuario.
Cómo probarlo:
Utiliza el custom hook useUserRoles en un componente para obtener y visualizar los roles de usuario.
Verifica que los roles se obtienen correctamente desde el backend y se muestran en la interfaz de usuario.
> feat: Se implemeta servicio y custom hook para obtener los roles de usuario

- src/hooks/useUserRoles.ts
- src/interfaces/Role.ts
- src/interfaces/UserRole.ts
- src/pages/userPages/UserOptionCreate.tsx
- src/services/roles/index.ts
- src/services/userRoles/getUserRoles.service.ts
- src/services/userRoles/index.ts
Descripción:
Resumen:
Se realiza un refactor renombrando role y roles a userRole y userRoles respectivamente para mejorar la claridad y el contexto de la entidad.
Mejorar la descriptividad y el entendimiento del código al hacer que los nombres de las entidades sean más precisos.
Renombrado role a userRole en todo el código base.
Renombrado roles a userRoles en todo el código base.
> refactor: Se hace refactor de role y roles a userRole y userRoles para hacer más descriptiva y mejorar el contexto de la entidad

- src/components/FileUpload.tsx
- src/hooks/useFileUpload.ts
- src/pages/css/UserOptionsCreate.css
- src/pages/userPages/UserOptionCreate.tsx
- src/services/fileUpload/fileUpload.service.ts
Descripción:
Resumen:
Se implementa la funcionalidad para cargar la imagen del usuario al servidor y obtener la URL correspondiente en el frontend utilizando React.
Permitir a los usuarios subir su imagen de perfil y obtener la URL de la imagen almacenada en el servidor para mejorar la personalización de perfiles.
Implementado custom hook useFileUpload para manejar la lógica de carga de imágenes.
Creado servicio fileUpload.service para interactuar con el backend.
Creado componente FileUpload para la interfaz de carga de imágenes en React.
Cómo probarlo:
Usa el componente UploadImage para cargar una imagen.
Verifica que la imagen se carga correctamente y se obtiene la URL desde el backend.
> feat: Implementación de funcionalidad para cargar imagen del usuario al servidor y obtener la url

- src/adapter.tsx
- src/components/FileUpload.tsx
- src/hooks/useFileUpload.ts
- src/pages/userPages/UserOptionCreate.tsx
Resumen:
Se añade la propiedad imageUrl al cuerpo del usuario en las peticiones realizadas desde el frontend.
Facilitar la gestión y visualización de la URL de la imagen del usuario en las operaciones realizadas desde el frontend.
Actualización de las peticiones al backend para incluir imageUrl en el cuerpo del usuario.
Cómo probarlo:
Realiza una petición que incluya imageUrl en el cuerpo del usuario.
Verifica que la propiedad imageUrl se envíe correctamente al backend.
> feat: Se añade imageUrl al cuerpo del usuario al hacer petición

- src/pages/userPages/UserOptions.tsx
Se implemento un modal para cambiar los roles del usuario desde la lista principal de usuarios
> feat: Se añade funcionalidad para cambiar roles de usuario individualmente con un  modal

- src/pages/css/Login.css
- src/pages/css/UserOptionsCreate.css
- src/pages/userPages/UserOptionCreate.tsx
- src/pages/userPages/UserOptions.tsx
Se implementa temporizador en modales para los mensajes de éxito y error de formulario para crear usuario
> feat: Se implementa temporizador para mensajes de modales

- package-lock.json
- package.json
- tsconfig.app.json
- vite.config.ts
Resumen:
Se configura el proyecto para permitir importaciones con rutas absolutas mediante el uso de alias.
Facilitar la gestión de importaciones y mejorar la legibilidad del código.
Configuración de alias para importaciones absolutas en el proyecto.
> chore: Se configura el proyecto para implementar importaciones con rutas absolutas usando alias

- src/components/Breadcrumb.tsx
- src/components/css/breadcrumb.css
- src/layouts/BasePage.css
- src/layouts/BasePage.tsx
- src/layouts/Sidebar.tsx
- src/pages/Login.tsx
tambien se actualizo el componente breadcrumb y se separo el css
> fix: al actualizar se queda en la pagina

- .eslintrc.cjs
- package-lock.json
- package.json
-Se instala plugin para mejorar el formateo de las importaciones de rutas
> chore: Se instala plugin de eslint para no importar rutas relativas

- tsconfig.app.json
- vite.config.ts
-Se implementan rutas absolutas para adapters y apps
> feat: Se implementan nuevas rutas absolutas

- src/apps/App.tsx
- src/components/FileUpload.tsx
- src/components/RoleChangeModal.tsx
- src/hooks/useFetchUsers.ts
- src/hooks/useFileUpload.ts
- src/hooks/useUserCreate.ts
- src/hooks/useUserManagement.ts
- src/hooks/useUserRoles.ts
- src/hooks/useUserUpdate.ts
- src/layouts/HeaderApp.tsx
- src/layouts/Sidebar.tsx
- src/pages/Login.tsx
- src/pages/MainPage.tsx
- src/pages/userPages/UserOptionCreate.tsx
- src/pages/userPages/UserOptionCreateRole.tsx
- src/pages/userPages/UserOptionEdit.tsx
- src/pages/userPages/UserOptions.tsx
- Se hace refactor de todo el código del proyecto para implementar rutas absolutas
> refactor: Se hace refactor con eslint en todo el código del proyecto para implementar rutas absolutas

- src/hooks/useUsers.ts
- src/pages/MainPage.tsx
- src/pages/userPages/UserOptions.tsx
- src/services/users/getUsers.service.ts
- src/services/users/index.ts
- tsconfig.app.json
- vite.config.ts
Resumen:
Se reorganizan los hooks y el servicio relacionados con usuarios para mejorar la estructura y legibilidad del código.
Reestructuración y organización de los hooks y el servicio de usuarios.
> refactor: Se reorganiza hooks y service de users

- src/components/FileUpload.tsx
- src/components/UserForm.tsx
- src/hooks/useUserForm.ts
- src/pages/userPages/UserOptionCreate.tsx
Descripción:
Resumen:
Se reestructura y organiza el componente del formulario de usuarios para mejorar su mantenibilidad y claridad.
Reorganización del componente del formulario de usuarios.
> refactor: Se organiza el componente para formulario de usuarios

- .eslintrc.cjs
- src/components/Editables.tsx
- src/components/SubcategoryModal.tsx
- src/components/css/breadcrumb.css
- src/hooks/cleanNameUtil.ts
- src/hooks/useCategoryCreate.ts
- src/hooks/useCategoryUpdate.ts
- src/hooks/useFamilyCreate.ts
- src/hooks/useFamilyManagement.ts
- src/hooks/useFamilyUpdate.ts
- src/hooks/useFetchCategories.ts
- src/hooks/useFetchCategoriesFromFamily.ts
- src/hooks/useFetchFamilies.ts
- src/hooks/useFetchSubcategories.ts
- src/hooks/useFetchSubcategoriesFromFamily.ts
- src/hooks/useSubcategoryCreate.ts
- src/pages/specificationsPages/CategorizationMenu.tsx
- src/pages/specificationsPages/CreateFamily.tsx
- src/pages/specificationsPages/EditFamily.tsx
- src/pages/specificationsPages/EditFamily2.tsx
- Se refactoriza todo el código para mejor legibilidad y organización con npm run lint y npm run format
> refactor: Se refactoriza todo el código con npm run lint y format de eslint y prettier

- src/components/DeletionModal.tsx
- src/components/EditCategory.tsx
- src/components/ErrorMessage.tsx
- src/components/ShowManageCategory.tsx
- src/components/SubcategoryModal.tsx
- src/components/SuccessMessage.tsx
- src/components/css/deletionModal.css
- src/components/css/errorMessage.css
- src/components/css/successMessage.css
- src/components/svg/CheckIcon.tsx
- src/components/svg/CrossIcon.tsx
- src/hooks/useFamilyManagement.ts
- src/pages/css/editFamily.css
- src/pages/specificationsPages/CategorizationMenu.tsx
- src/pages/specificationsPages/EditFamily.tsx
El dialogo que te cuenta y pregunta si vas a borrar o no
por ahora se puede evitar este dialogo si no tiene hijos (categorias o subcategorias)
pero en un futuro debera incluir herramientas que se afecten por esto
> Count delete implementation

- src/components/ShowManageCategory.tsx
- src/hooks/useCategoryManegement.ts
- src/hooks/useFamilyManagement.ts
Resumen:
Se añade la funcionalidad de eliminación en cascada para las categorizaciones en el frontend.
Permitir la eliminación automática de subcategorías y categorías relacionadas al eliminar una entidad principal.
Implementación de la lógica de eliminación en cascada en el frontend para categorizaciones.
> feat: Se implementa eliminación en cascada de categorizaciones

- index.html
- src/components/ThemeToggle.tsx
- src/components/css/autocompleteInput.css
- src/components/css/createSpecs.css
- src/components/css/editables.css
- src/components/css/errorMessage.css
- src/components/css/successMessage.css
- src/components/svg/BriefcaseIcon.tsx
- src/components/svg/PawIcon.tsx
- src/index.css
- src/layouts/BasePage.css
- src/layouts/HeaderApp.tsx
- src/pages/css/UserOptionsCreate.css
- src/pages/css/editFamily.css
- src/pages/css/familyList.css
- src/pages/css/listofspecs.css
solo estilos y añadir y separar un componente boton para cambiar temas
> style: la habilidad de cambiar entre temas oscuro y claro

- src/components/CreateSpecs.tsx
Se añade el usuario al mandar la información
> fix: createdby  of create specs

- src/adapters/products.adapter.tsx
- src/apps/App.tsx
- src/components/Slideshow.tsx
- src/components/ToolInfoModal.tsx
- src/hooks/useCharacteristics.ts
- src/hooks/useManuals.ts
- src/hooks/useMultipleFileUpload.ts
- src/hooks/useProductManagement.ts
- src/hooks/useSpecs.ts
- src/hooks/useVideos.ts
- src/pages/toolPages/CreateTool.tsx
- src/pages/toolPages/ToolMenu.css
- src/pages/toolPages/ToolMenu.tsx
- src/pages/toolPages/createtool.css
solo falta la funcfionalidad de añadir manuales y editar formulario.... ademas de buscar en la lista
> Create tool form

- src/apps/App.tsx
- src/components/Editables.tsx
- src/components/EditablesList.tsx
- src/hooks/useProductManagement.ts
- src/hooks/useToolCategorizationEdit.tsx
- src/pages/css/editFamily.css
- src/pages/toolPages/EditTool.tsx
- src/pages/toolPages/ToolMenu.css
- src/pages/toolPages/createtool.css
- src/services/specifications/fetchSpecificationsByCategoryId.service.ts
- src/services/specifications/updateProduct.service.ts
Para editar herramientas:
Le falta: 
Advertencias
mensajes de exito y fracaso
poder eliminar la herramienta desde ahi
Poder subir/quitar imagenes
poder subir/quitar manuales
poder subir/quitar videos
> Edit tool form

- src/components/EditCategory.tsx
- src/components/EditSubcategory.tsx
- src/components/ShowManageCategory.tsx
- src/components/SubcategoryModal.tsx
- src/hooks/useFamilyManagement.ts
- src/pages/familyPages/CategorizationMenu.tsx
- src/pages/familyPages/EditFamily.tsx
Esta es funcional hasta ahorita, pero le falta que pueda actualizar datos, se hace mañana Xd
> Add specification count

- src/components/DeletionModal.tsx
- src/components/DropdownMenu.tsx
- src/components/EditCategory.tsx
- src/components/EditSubcategory.tsx
- src/components/ShowManageCategory.tsx
- src/components/SubcategoryModal.tsx
- src/hooks/useFamilyManagement.ts
- src/pages/css/editFamily.css
- src/pages/familyPages/CategorizationMenu.tsx
- src/pages/familyPages/EditFamily.tsx
- src/pages/toolPages/EditTool.tsx
> Refactor edit

- src/components/Editables.tsx
- src/components/ToolInfoModal.tsx
- src/hooks/useMultipleFileUpload.ts
- src/layouts/BasePage.css
- src/pages/toolPages/CreateTool.tsx
- src/pages/toolPages/EditTool.tsx
- src/services/fileUpload/fileUpload.service.ts
feat: se pueden añadir manuales y videos, ademas tambien en editar, solo no se pueden eliminar aun en editar...
> Manual video add

- src/components/AutoCompleteInput.tsx
- src/components/DropdownMenu.tsx
- src/components/Editables.tsx
- src/components/ToolInfoModal.tsx
Se corrigen problemas de renderización en la sintaxis y semnatica html de elementos
> Fix render

- src/adapters/subcategory.adapter.ts
- src/hooks/useMultipleFileUpload.ts
- src/pages/toolPages/CreateTool.tsx
- src/pages/toolPages/EditTool.tsx
- src/services/fileUpload/fileUpload.service.ts
Se arrgelan funcionalidades de subir archivos al crear y editar un producto
> Fix fileupload

- src/pages/familyPages/EditFamily.tsx
Flata corregir tipados en EditFamily
> fix: Se corrigen importancions y falata corregir errores de tipado

- src/components/commons/DynamicImageInputAreaList.tsx
- src/components/commons/DynamicImageSelectInputAreaList.tsx
- src/components/commons/DynamicInputAreaList.tsx
- src/components/commons/DynamicSelectInputAreaList.tsx
- src/components/commons/ImageUploaderSingle.tsx
- src/components/commons/SelectInput.tsx
- src/components/css/ImageUploader.css
- src/components/css/ImageUploaderSingle.css
- src/hooks/categories/useCategoryCreate.ts
- src/pages/css/createFamily.css
- src/pages/familyPages/CreateFamily.tsx
- src/pages/toolPages/createtool.css
> Create family refactor

- src/components/commons/DynamicImageInputAreaList.tsx
- src/components/commons/SelectInput.tsx
- src/handlers/categories.handler.ts
- src/handlers/subcategories.handler.ts
- src/pages/familyPages/CreateFamily.tsx
- tsconfig.app.json
- vite.config.ts
> fix: se movieron algunas cosas y se arreglaron keys

- src/services/pdfs/technicalDatasheet.service.ts
Se implementan servicios para obtener y descargar la ficha técnica del producto
> Technical datasheet product

- src/apps/App.tsx
- src/components/commons/TextInput.tsx
- src/components/files/ImagesInput.tsx
- src/components/orders/RepairOrderForm.tsx
- src/components/orders/RepairOrderList.tsx
- src/components/orders/RepairProductForm.tsx
- src/contexts/company/CompanyContext.tsx
- src/contexts/customer/CustomerContext.tsx
- src/contexts/order/OrderContext.tsx
- src/contexts/otherProduct/OtherProductContext.tsx
- src/contexts/repairProduct/RepairProductContext.tsx
- src/hooks/orders/useCreateOrder.ts
- src/hooks/otherProducts/useOtherProducts.ts
- src/interfaces/Company.interface.ts
- src/interfaces/Customer.interface.ts
- src/interfaces/Order.interface.ts
- src/interfaces/OtherProduct.interface.ts
- src/interfaces/RepairProduct.interface.ts
- src/pages/repairOrderPages/CreateRepairOrderPage.tsx
- src/pages/repairOrderPages/RepairOrderMenuPage.tsx
- src/services/orders/orders.service.ts
- src/services/otherProducts/otherProducts.service.ts
Se agregan todos los cambios a la rama principal
> Repair order implements

- src/components/commons/SelectInput.tsx
- src/components/products/CreateProduct.tsx
- src/components/products/EditProduct.tsx
- src/components/products/ProductForm.tsx
- src/pages/productPages/ProductMenu.tsx
Se mejora formulario de producto y se añade pdf en la lista de menu de productos
> update: Se agrega mejora para marca en productos

- src/components/orders/hooks/useResetRepairOrder.ts
- src/contexts/customer/CustomerContext.tsx
Se cambia customer type a company por defecto
> chore: Se mejora el reset y se cambia el customer type

- src/components/orders/RepairOrderForm.tsx
- src/hooks/orders/useCreateOrder.ts
Funcionalidad de colocar número de teléfono si se encuentra el customer
> feat: Se implementa funcionalidad de colocar número de teléfono
